name: Automatic Deployment on Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-deployment:
    name: Laravel-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub deployment
          id: deployment
          uses: chrnorm/deployment-action@v2
          with:
            token: '${{ github.token }}'
            environment: production
            environment-url: https://bellhavenpark.com.au
      
      - name: BellHavenPark Deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd /var/www/bellhavenpark.com.au
            php artisan down
            git branch
            git reset --hard
            git checkout main
            git pull "https://${{ secrets.GB_USERNAME }}:${{ secrets.GB_ACCESSTOKEN }}@github.com/haroon-mahmood-4276/BellHavenPark.git" main
            php artisan migrate
            php artisan optimize:clear
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
      
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          environment-url: https://bellhavenpark.com.au
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
      
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          environment-url: https://bellhavenpark.com.au
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}