name: Automatic Deployment on Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-deployment:
    name: Laravel-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Laravel Deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 110.174.120.22
          username: bellhaven
          key: ${{ secrets.IYESERVERSSH }}
          passphrase: ${{ secrets.SSHKEYPASSWORD }}
          script: |
            cd /var/www/bellhavenpark.com.au
            php artisan down
            git branch
            git reset --hard
            git checkout main
            git pull "https://${{ secrets.GB_USERNAME }}:${{ secrets.GB_ACCESSTOKEN }}@github.com/haroon-mahmood-4276/BellHavenPark.git" main
            php artisan optimize:clear
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan up
  update-jira-deployment-info:
    needs: laravel-deployment
    steps:
      - name: Update Jira Deployment Information
        uses: HighwayThree/jira-upload-deployment-info@master
        with:
          client-id: '${{ secrets.BHP_CLIENT_ID }}'
          client-secret: '${{ secrets.BHP_CLIENT_SECRET }}'
          cloud-instance-base-url: '${{ secrets.BHP_CLOUD_INSTANCE_BASE_URL }}'
          issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
          display-name: "Deployment Number ${{ github.GITHUB_RUN_NUMBER }} }}"
          description: "Test Deployment"
          last-updated: '${{github.event.head_commit.timestamp}}'
          label: 'Test Deployment Label'
          state: '${{env.DEPLOY_STATE}}'
          environment-id: '${{ inputs.ENVIRONMENT_KEY }} }}'
          environment-display-name: '${{ inputs.ENVIRONMENT_NAME }}'
          environment-type: '${{ vars.ENVIRONMENT_STAGE }}'
